version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - "6380:6379" # Map host port 6380 to container port 6379
    volumes:
      - redis-data:/data # redis data directory for persistence
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: always

volumes:
  redis-data:  # for Redis persistence

