global:
  scrape_interval: 15s # How often to scrape targets by default.

scrape_configs:
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'app'
    static_configs:
      - targets: ['app:8080']